name: Matrix

on:
  push:
    branches:
      - reuse-gha-tools

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  MatrixTests:
    name: Matrix test - PHP ${{ matrix.php }}, WP ${{ matrix.wp-version }}, WC ${{ matrix.wc-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.0, 7.1, 7.2, 7.3]
        wc-version: [6.1.0, 6.2.0, 6.3.0, 6.4.0, latest]
        include:
          - wc-version: 6.1.0
            wp-version: 5.8
          - wc-version: 6.2.0
            wp-version: 5.9
          - wc-version: 6.3.0
            wp-version: 5.9
          - wc-version: 6.4.0
            wp-version: latest
          - wc-version: latest
            wp-version: latest

    steps:
      - name: Echo matrix
        shell: bash
        run: |
          echo "${{ matrix.php }}"
          echo "${{ matrix.wp-version }}"
          echo "${{ matrix.wc-version }}"
