name: Test Node

on:
  push:

jobs:
  env:
    name: Test env
    runs-on: ubuntu-latest
    steps:
      - name: Log env
        run: |
          echo "github.sha => ${{ github.sha }}"
          echo "github.event.after => ${{ github.event.after }}"
          echo "github.event.ref => ${{ github.event.ref }}"
          echo "${{ github.event.ref }}" | sed 's/^refs\/heads\///'
          echo "CI_REF=$(echo '${{ github.event.ref }}' | sed 's/^refs\/heads\///')" >> $GITHUB_ENV

      - name: Print env
        run: echo "${{ env.CI_REF }}"

  Howdy:
    name: JavaScript unit tests
    runs-on: ubuntu-latest
    if: ${{ '' != '' }} # skip
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Built-in node versions
        run: |
          node --version
          npm --version

      - name: Built-in nvm and node versions
        shell: bash -e -l {0}
        run: |
          nvm install
          node --version
          npm --version

      - name: Built-in node versions after nvm install
        run: |
          node --version
          npm --version

      - name: Built-in nvm and node versions at another step
        shell: bash -e -l {0}
        run: |
          nvm use
          node --version
          npm --version

      - name: Read .nvmrc
        run: echo "NVM_NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Set up Node
        if: ${{ env.NVM_NODE_VERSION != 'lts/*' }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NVM_NODE_VERSION }}

      - name: nvmrc node versions by setup-node@v2
        run: |
          node --version
          npm --version
