name: PHP

on:
  push:
    branches:
      - reuse-gha-tools

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: PHP coding standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare PHP
        uses: eason9487/gha-tools/.github/actions/prepare-php@v1
        with:
          php-version: "7.4"
          tools: composer:v1, cs2pr

      - name: Prepare MySQL
        uses: eason9487/gha-tools/.github/actions/prepare-mysql@v1

      - name: Log PHPCS debug information
        run: vendor/bin/phpcs -i

      - name: Create table
        run: mysql -e 'CREATE DATABASE IF NOT EXISTS wordpress_test;' -u root -proot
