name: PHP Unit Tests

on:
  push:
    branches:
      - php-matrix

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  UnitTests:
    name: PHP unit tests - PHP ${{ matrix.php }}, WP ${{ matrix.wp-version }}, WC ${{ matrix.wc-versions }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4]
        wp-version: [latest]
        wc-versions: ["6.4.0, 6.5.0, latest"]
        include:
          # Minimum PHP support and L-2 WP/WC version
          - php: 7.2
            wp-version: 5.8
            wc-versions: 6.4.0

    steps:
      - name: Run PHP unit tests
        run: |
          WC_VERSIONS=$(echo "${{ matrix.wc-versions }}" | sed -r "s/ *, */ /g")
          WC_VERSIONS=($WC_VERSIONS)

          URL_CONFIG="url.https://${{ secrets.BOT_GH_TOKEN }}:x-oauth-basic@github.com/.insteadOf git@github.com:"
          git config --global $URL_CONFIG

          INIT_INSTALL=true

          for WC_VERSION in "${WC_VERSIONS[@]}"; do
            if [ "$INIT_INSTALL" = true ]; then
              echo "::group::Install WP ${{ matrix.wp-version }} and WC ${WC_VERSION}"
              echo "./bin/install-unit-tests.sh wordpress_test root root localhost ${{ matrix.wp-version }} $WC_VERSION"
              INIT_INSTALL=false
            else
              echo "::group::Switch to WP ${{ matrix.wp-version }} and WC ${WC_VERSION}"
              echo "./bin/switch-wp-wc-in-unit-tests.sh wordpress_test root root localhost ${{ matrix.wp-version }} $WC_VERSION"
            fi
            echo "::endgroup::"
          done

          git config --global --unset $URL_CONFIG
